#!/bin/bash

SIDE=${1}

if [ -z "${SIDE}" ] || ([ ${SIDE} != "client" ] && [ ${SIDE} != "server" ]); then
    echo "First parameter should be one of 'client' or 'server'"
    exit 1
fi

SCRIPT_DIR="${HOME}/census-${SIDE}"

if [ -d ${SCRIPT_DIR} ]; then
    rm -r ${SCRIPT_DIR}
    echo "[DONE] Directory '${SCRIPT_DIR}' cleaned."
else
    echo "[INFO] Directory '${SCRIPT_DIR}' not found. Skipping..."
fi
